# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='inlet_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='outlet_data',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
