# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_remove_component_outlet_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='outlet_ports',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
