# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-17 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_component_outlet_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='inlet_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
